### ISSUE TITLE
Bad code formatting - try Prettier

### ISSUE THREAD

**Issue by ukupat** [kaarelkilki/ejs-challenge-blog#1]
<img width="351" alt="Screen Shot 2021-08-26 at 17 36 09" src="https://user-images.githubusercontent.com/4997766/130982695-2bcff6f6-0fd2-4420-9da9-1c1a11fc6b54.png">

☝️ ☝️ makes it hard to read the code. I recommend trying out https://prettier.io/ ;)

**Comment by kaarelkilki** [comment]
Thanks for the advice. I will definitely try prettier in my Atom editor ;)
And thanks to that screenshot you sent I remembered that I do not use .overflow-ellipsis class in my code, so I can remove it from css file.
